# -*- coding: utf-8 -*-
from . import asset_company
from . import asset_division
from . import asset_district
from . import asset_department
from . import asset_unit
from . import asset_designation
from . import asset_tag
from . import asset_brand
from . import asset_service
from . import asset_accessory
from . import asset_financial_year
from . import asset_color
from . import asset_insurance_partner
from . import asset_item
from . import asset_category
from . import asset_class
from . import asset_office_location
from . import asset_floor_location
from . import asset_supplier
from . import asset
from . import asset_depreciation
from . import asset_depreciation_wizard
from . import asset_user
from . import asset_insurance_type
from . import asset_dashboard